const profissoes = [
  "Acupunturista",
  "Açougueiro(a)",
  "Administrador(a)",
  "Adestrador de Animais",
  "Advogado(a)",
  "Advogado(a) ambiental",
  "Advogado(a) civil",
  "Advogado(a) penal",
  "Advogado(a) previdenciário",
  "Advogado(a) trabalhista",
  "Agente de seguros",
  "Agente de viagens",
  "Agricultor(a)",
  "Alfaiate/Alfaitaria",
  "Alinhador(a) de pneus",
  "Almoxarife",
  "Amolador Afiador",
  "Animador(a) de festas",
  "Antiquário(a)",
  "Antropólogo(a)",
  "Apicultor(a)",
  "Arqueólogo(a)",
  "Arquiteto(a)",
  "Arquiteto(a) de software",
  "Artesão",
  "Artista de circo",
  "Artista plástico(a)",
  "Ascensorista",
  "Assessor de Marketing",
  "Assessor(a) de imprensa",
  "Assistente administrativo(a)",
  "Assistente social",
  "Astrônomo(a)",
  "Atendente de telemarketing",
  "Atleta",
  "Ator/Atriz",
  "Auditor(a)",
  "Auditor(a) fiscal",
  "Autônomo(a)",
  "Auxiliar de cozinha",
  "Babá",
  "Bailarino(a)",
  "Balconista",
  "Banda Musical",
  "Barbeiro(a)",
  "Barman",
  "Barista",
  "Bancário",
  "Bibliotecário(a)",
  "Bicicleteiro(a)",
  "Biólogo(a)",
  "Biomédico(a)",
  "Bioquímico(a)",
  "Biotecnólogo(a)",
  "Bombeiro(a)",
  "Borracheiro(a)",
  "Cabeleireiro(a)",
  "Caixa de supermercado",
  "Calheiro",
  "Camareiro(a)",
  "Caminhoneiro(a)",
  "Cantor",
  "Carpinteiro(a)",
  "Carteiro(a)",
  "Caseiro(a)",
  "Cenógrafo(a)",
  "Ceramista",
  "Cerimonialista",
  "Chapeiro(a)",
  "Chaveiro(a)",
  "Chef de cozinha",
  "Churrasqueiro(a)",
  "Cientista",
  "Cientista de dados",
  "Cientista político(a)",
  "Cineasta",
  "Coach",
  "Comediante",
  "Comerciante",
  "Comissário(a) de bordo",
  "Compositor(a)",
  "Confecciona cartazes, faixas, banners",
  "Confeiteiro(a)",
  "Consultor Imagem",
  "Consultor(a) de beleza",
  "Consultor(a) de RH",
  "Consultor(a) financeiro(a)",
  "Contador (a)",
  "Controlador(a) de qualidade",
  "Controlador(a) de tráfego aéreo",
  "Conserto de Cadeiras",
  "Conserto de Instrumento Musical",
  "Corretor(a) de imóveis",
  "Corretor(a) de seguros",
  "Costureiro(a)",
  "Cozinheiro(a)",
  "Cuidador(a) de idosos",
  "Dançarino(a)",
  "Decorador(a)",
  "Defensor(a) público(a)",
  "Depilador (a)",
  "Dentista",
  "Despachante",
  "Designer de moda",
  "Designer gráfico(a)",
  "Designer de interiores",
  "Desenvolvedor(a) de software",
  "Digitador(a)",
  "Diarista",
  "DJ",
  "Doceria",
  "Economista",
  "Ecólogo(a)",
  "Editor(a) de vídeo",
  "Educador(a) físico(a)",
  "Eletricista",
  "Eletrônico(a)",
  "Embalador(a)",
  "Encanador(a)",
  "Enfermeiro(a)",
  "Engenheiro(a)",
  "Engenheiro(a) agrícola",
  "Engenheiro(a) agrônomo(a)",
  "Engenheiro(a) ambiental",
  "Engenheiro(a) biomédico(a)",
  "Engenheiro(a) civil",
  "Engenheiro(a) de alimentos",
  "Engenheiro(a) de computação",
  "Engenheiro(a) de materiais",
  "Engenheiro(a) de minas",
  "Engenheiro(a) de petróleo",
  "Engenheiro(a) de produção",
  "Engenheiro(a) de segurança do trabalho",
  "Engenheiro(a) de software",
  "Engenheiro(a) de telecomunicações",
  "Engenheiro(a) elétrico(a)",
  "Engenheiro(a) mecânico(a)",
  "Engenheiro(a) químico(a)",
  "Engraxate",
  "Enólogo(a)",
  "Escritor(a)",
  "Escultor(a)",
  "Espeleólogo(a) - Arte Histórica",
  "Espeleólogo(a) - Artes Visuais",
  "Espeleólogo(a) - Desenho",
  "Espeleólogo(a) - Gravura",
  "Espeleólogo(a) - Material ou equipamento de espeleologia",
  "Espeleólogo(a) - Outro(s)",
  "Espeleólogo(a) - Pintura",
  "Estatístico(a)",
  "Esteticista",
  "Estilista",
  "Estivador(a)",
  "Estofador",
  "Executor(a) de serviços gerais",
  "Farmacêutico(a)",
  "Faxineiro(a)",
  "Ferramenteiro(a)",
  "Fisioterapeuta",
  "Florista",
  "Fonoaudiólogo(a)",
  "Fotógrafo(a)",
  "Fretes e carreto",
  "Fundidor(a)",
  "Garagista",
  "Garçom/Garçonete",
  "Gari",
  "Geógrafo(a)",
  "Geólogo(a)",
  "Gerente de banco",
  "Gerente de projetos",
  "Gestor(a) ambiental",
  "Gestor(a) de TI",
  "Guarda-costas",
  "Guia turístico(a)",
  "Historiador(a)",
  "Ilustrador(a)",
  "Iluminador(a)",
  "Informático(a)",
  "Instalador de assoalhos",
  "Instalador de energia solar e eólica",
  "Instalador de Insulfilm Película",
  "Instalador de interfone",
  "Instalador de papel de parede",
  "Instalador de porcelanato",
  "Instalador de Rastreador Veicular",
  "Instalador de Sistemas de Segurança",
  "Instalador(a) de ar condicionado",
  "Instalador(a) de box banheiro e sacada",
  "Instalador(a) de divisória",
  "Instalador(a) de drywall",
  "Instalador(a) de gesso",
  "Instalador(a) de piso Laminado, vinílico",
  "Instrumentador Cirúrgico",
  "Instrutor(a) de academia",
  "Instrutor(a) de autoescola",
  "Intérprete",
  "Investigador(a)",
  "Jardineiro(a)",
  "Joalheiro(a)",
  "Jornalista",
  "Ladrilhador(a)",
  "Lavador(a) de carros",
  "Lavador(a) de roupas",
  "Lavrador(a)",
  "Leiteiro(a)",
  "Leiturista",
  "Líder de equipe",
  "Locador Brinquedos",
  "Locador Ferramentas",
  "Locador de andaimes",
  "Locador de equipamentos audiovisuais",
  "Locador de gerador de energia",
  "Locador de veículos",
  "Locutor(a)",
  "Maestro(a)",
  "Manicure e pedicuro",
  "Maquiador(a)",
  "Marceneiro(a)",
  "Marido de aluguel",
  "Massagista",
  "Massoterapeuta",
  "Matemático(a)",
  "Mecânico(a)",
  "Médico(a)",
  "Metalúrgico(a)",
  "Meteorologista",
  "Modelo",
  "Montador(a) de móveis",
  "Motoboy/Motogirl",
  "Motorista",
  "Motorista de ônibus",
  "Museólogo(a)",
  "Músico(a)",
  "Nutricionista",
  "Oceanógrafo(a)",
  "Office boy/Office girl",
  "Oficial de justiça",
  "Operador(a) de caixa",
  "Operador(a) de câmera",
  "Operador(a) de máquinas",
  "Ortopedista",
  "Ourives",
  "Palhaço(a)",
  "Paleontólogo(a)",
  "Palestrante",
  "Pastor(a)",
  "Pediatra",
  "Pedagogo(a)",
  "Pedreiro(a)",
  "Perito(a) criminal",
  "Pescador(a)",
  "Pescador(a) artesanal",
  "Pesquisador(a)",
  "Pintor(a)",
  "Pizzaiolo(a)",
  "Podólogo (a)",
  "Poeta/Poetisa",
  "Policial",
  "Policial rodoviário(a)",
  "Professor(a) de línguas",
  "Professor(a) particular",
  "Professor(a) universitário(a)",
  "Programador(a)",
  "Promotor(a) de eventos",
  "Psicólogo(a)",
  "Psicopedagogo(a)",
  "Publicitário(a)",
  "Químico(a)",
  "Quiroprático(a)",
  "Radialista",
  "Radiologista",
  "Recreador(a)",
  "Redator(a)",
  "Relações públicas",
  "Reparador(a) de computadores",
  "Reparador(a) de impressoras",
  "Repórter",
  "Revisor(a) de textos",
  "Salva-vidas",
  "Sapateiro(a)",
  "Secretário(a)",
  "Segurança",
  "Serralheiro(a)",
  "Servente de pedreiro",
  "Serviço carro de som",
  "Serviço conserto Tvs",
  "Serviço conserto eletrodomésticos",
  "Serviço conserto micro-ondas",
  "Serviço de Designer",
  "Serviço de corte e costura",
  "Serviço de entrega (delivery)",
  "Serviço de funilaria e pintura",
  "Serviço de limpeza de caixas d'água",
  "Serviço de manutenção predial",
  "Serviço de marcenaria",
  "Serviço de pintura residencial",
  "Serviço de podas de árvore",
  "Serviço de reboco e alvenaria",
  "Serviço de roçagem",
  "Serviço de tapeçaria",
  "Serviço de terraplanagem",
  "Serviço de vidraçaria",
  "Serviço encanador",
  "Serviço manutenção ar condicionado",
  "Serviço manutenção elétrica",
  "Serviço manutenção geral",
  "Serviço manutenção hidráulica",
  "Serviços Administrativos",
  "Serviços de Acompanhante para idosos",
  "Serviços de Babysitter",
  "Serviços de Buffets",
  "Serviços de Detetive particular",
  "Serviços de Encanamento",
  "Serviços de Entulho",
  "Serviços de Funilaria",
  "Serviços de Hidráulica",
  "Serviços de Iluminação",
  "Serviços de Manutenção em geral",
  "Serviços de Segurança",
  "Serviços de Solda",
  "Serviços domésticos",
  "Sociólogo(a)",
  "Soldador(a)",
  "Sommelier",
  "Supervisor(a) de produção",
  "Técnico(a) agrícola",
  "Técnico(a) contábil",
  "Técnico(a) de enfermagem",
  "Técnico(a) de informática",
  "Técnico(a) de laboratório",
  "Técnico(a) de manutenção",
  "Técnico(a) de segurança do trabalho",
  "Técnico(a) eletricista",
  "Técnico(a) em edificações",
  "Técnico(a) em mecatrônica",
  "Técnico(a) mecânico(a)",
  "Telefonista",
  "Terapeuta ocupacional",
  "Torneiro mecânico",
  "Tradutor(a)",
  "Trainee",
  "Treinador(a) de animais",
  "Vaqueiro(a)",
  "Vendedor(a)",
  "Vendedor(a) ambulante",
  "Vigilante",
  "Zelador(a)",
  "Zootecnista"
]

const deficiencias = [
  "Transtorno do espectro autista",
  "Surdocegueira",
  "Surdez",
  "Perturbação emocional",
  "Deficiência auditiva",
  "Deficiência intelectual",
  "Múltiplas deficiências",
  "Deficiência ortopédica",
  "Outra deficiência de saúde",
  "Deficiência específica de aprendizagem",
  "Deficiência de fala ou linguagem",
  "Lesão cerebral traumática",
  "Deficiência visual",
  "Deficiências físicas",
  "Deficiências cognitivas",
  "Deficiências do desenvolvimento",
  "Dificuldades de aprendizagem",
  "Deficiências sensoriais"
];

const familias = [
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8 ou mais",
];

const escolaridade = [
  "Ensino fundamental incompleto",
  "Ensino fundamental completo",
  "Ensino médio incompleto",
  "Ensino médio completo",
  "Ensino superior incompleto",
  "Ensino superior completo",
  "Pós-Graduação"
];

const racas = [
  "Branco(a)",
  "Preto(a)",
  "Amarelo(a)",
  "Pardo(a)",
  "Indígena",
  "Outra",
];

const countries = [
  "Afeganistão", "África do Sul", "Albânia", "Alemanha", "Andorra", "Angola", "Antígua e Barbuda", "Arábia Saudita", "Argélia", "Argentina", "Armênia", "Austrália", "Áustria", "Azerbaijão",
  "Bahamas", "Bahrein", "Bangladesh", "Barbados", "Belarus", "Bélgica", "Belize", "Benin", "Butão", "Bolívia", "Bósnia e Herzegovina", "Botsuana", "Brasil", "Brunei", "Bulgária", "Burquina Faso", "Burundi",
  "Cabo Verde", "Camarões", "Camboja", "Canadá", "Catar", "Cazaquistão", "Chade", "Chile", "China", "Chipre", "Colômbia", "Comores", "Congo-Brazzaville", "Congo-Kinshasa", "Coreia do Norte", "Coreia do Sul", "Costa do Marfim", "Costa Rica", "Croácia", "Cuba",
  "Dinamarca", "Djibouti", "Dominica", "República Dominicana",
  "Egito", "El Salvador", "Emirados Árabes Unidos", "Equador", "Eritreia", "Eslováquia", "Eslovênia", "Espanha", "Estados Unidos", "Estônia", "Eswatini", "Etiópia",
  "Fiji", "Filipinas", "Finlândia", "França",
  "Gabão", "Gâmbia", "Gana", "Geórgia", "Granada", "Grécia", "Guatemala", "Guiana", "Guiné", "Guiné-Bissau", "Guiné Equatorial",
  "Haiti", "Honduras", "Hungria",
  "Iêmen", "Ilhas Marshall", "Índia", "Indonésia", "Irã", "Iraque", "Irlanda", "Islândia", "Israel", "Itália",
  "Jamaica", "Japão", "Jordânia",
  "Kiribati", "Kosovo", "Kuwait", "Laos", "Lesoto", "Letônia", "Líbano", "Libéria", "Líbia", "Liechtenstein", "Lituânia", "Luxemburgo",
  "Macedônia do Norte", "Madagascar", "Malásia", "Malaui", "Maldivas", "Mali", "Malta", "Marrocos", "Maurícia", "Mauritânia", "México", "Mianmar", "Micronésia", "Moçambique", "Moldávia", "Mônaco", "Mongólia", "Montenegro",
  "Namíbia", "Nauru", "Nepal", "Nicarágua", "Níger", "Nigéria", "Noruega", "Nova Zelândia",
  "Omã",
  "Países Baixos", "Palau", "Panamá", "Papua-Nova Guiné", "Paquistão", "Paraguai", "Peru", "Polônia", "Portugal",
  "Quênia", "Quirguistão",
  "Reino Unido", "República Centro-Africana", "República Tcheca", "Romênia", "Ruanda", "Rússia",
  "São Cristóvão e Névis", "San Marino", "Santa Lúcia", "São Tomé e Príncipe", "São Vicente e Granadinas", "Senegal", "Serra Leoa", "Sérvia", "Singapura", "Síria", "Somália", "Sri Lanka", "Suazilândia", "Sudão", "Sudão do Sul", "Suécia", "Suíça", "Suriname",
  "Tailândia", "Tajiquistão", "Tanzânia", "Timor-Leste", "Togo", "Tonga", "Trinidad e Tobago", "Tunísia", "Turcomenistão", "Turquia", "Tuvalu",
  "Ucrânia", "Uganda", "Uruguai", "Uzbequistão",
  "Vanuatu", "Vaticano", "Venezuela", "Vietnã",
  "Zâmbia", "Zimbábue"
];

export { countries, deficiencias, escolaridade, familias, profissoes, racas }